language: node_js
node_js:
  - "10"

install: npm run install-all
cache:
  directories:
    - $HOME/.npm
script:
  # - npm run test-all
  - bash build.bash

branches:
  except:
    - master

notifications:
  email:
    - alexander@iteam.se
