env:
  - DOCKER_COMPOSE_VERSION=1.23.2

# The jobs section declares jobs available in this build context
jobs:
  include:
    # lint and run end-to-end tests
    - stage: "lint-and-e2e"
      name: "Lint and run end-to-end tests"
      cache: npm
      language: node_js
      install:
        - npm i -g lerna
        - npm install file:client --prefix examples/cv
        - npm run install
      test: skip
      script:
        - npm run lint
        - npm run test:e2e

    # build and deploy things
    - stage: deliver
      name: "Build and deploy code that has been updated"
      language: node_js
      install:
        # Install a fresh version of the openshift cli
        - mkdir -p /opt/openshift
        - wget -qO- https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz | tar xvzf - -C /opt/openshift --strip-components=1
        - export PATH=$PATH:/opt/openshift
      test: skip
      services:
        # Require docker to be running in the build context
        - docker
      script:
        # Authenticate towards Docker Hub
        - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

        # Authenticate towards OpenShift
        - oc login $OPENSHIFT_URL --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify=true

        # If this is not a tag, build images tagged :latest
        - export PHASE="ci"
        # If this is a tag, build images tagged v<tag> and :latest-tag
        - if [ ! -z "$TRAVIS_TAG" ]; then export PHASE="test"; fi

        - bash .deliver-$PHASE.bash app/ jobtechswe/mydata-app
        - bash .deliver-$PHASE.bash examples/cv/ jobtechswe/mydata-cv
        - bash .deliver-$PHASE.bash operator/ jobtechswe/mydata-operator

        # ...and finally remove cached credentials
        - oc logout
        - docker logout

# Flow control
# This section defines the order in which stages are run and when to run certain stages
stages:
  - name: lint-and-e2e
    if: branch != master
  - name: deliver
    if: (branch = master AND type != pull_request) OR tag IS present
