version: '3.5'
services:

  operator:
    image: node:12.6.0-alpine
    volumes:
      - ./operator:/app
    ports:
      - 3000:3000
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - APM_SERVER=http://apm-server:8200
      - APM_TOKEN=abc
      - PGHOST=postgres-operator
      - DATABASE_URL=postgres://postgresuser:postgrespassword@postgres-operator:5432/mydata
      - REDIS=redis://:fubar@redis-operator:6379/
    command: sh -c 'node wait-for-postgres && npm run migrate up && npm run start:watch'

  cv:
    image: node:12.6.0-alpine
    volumes:
      - ./examples/cv:/app
    ports:
      - 4000:4000
    working_dir: /app
    environment:
      - NODE_ENV=development
      - REDIS=redis://:fubar@redis-cv:6379/
      - CLIENT_ID=http://cv:4000
      - OPERATOR_URL=http://operator:3000
      - APM_SERVER=http://apm-server:8200
      - APM_TOKEN=abc
      - "PUBLIC_KEY=-----BEGIN RSA PUBLIC KEY-----\nMIGJAoGBAMinl3TDhzy/hZr+2ZrUMwveG+1eawsHqxUXOsdqARKfsBHTRYFPr+GW\nff9iNezU5yBBORtc/jVnPwto/lBhn2+jLCtcPuK5od8AEeiWGJbfL2np8P0/qg0O\n80qhLrMU47uuoEdTe9mbnB8A+N4OrC2WhPBj3zd9yAp1zLNPOk6NAgMBAAE=\n-----END RSA PUBLIC KEY-----\n"
      - "PRIVATE_KEY=-----BEGIN RSA PRIVATE KEY-----\nMIICXgIBAAKBgQDIp5d0w4c8v4Wa/tma1DML3hvtXmsLB6sVFzrHagESn7AR00WB\nT6/hln3/YjXs1OcgQTkbXP41Zz8LaP5QYZ9voywrXD7iuaHfABHolhiW3y9p6fD9\nP6oNDvNKoS6zFOO7rqBHU3vZm5wfAPjeDqwtloTwY983fcgKdcyzTzpOjQIDAQAB\nAoGBALGfGYV1KJvv9jdUbhCO03kn7pTbReqHqTyMSa4I+lYgId5FpXtorQsHCxYt\nPAsgFFELK6A7W5SuhrJ1CNri8Bxzh/7gYyj7njBTsjNfuoiK3cIkZBoTvY9K/OB+\nzinNKibWf3SZv9l1qFkaJvaC/+R5DMLb9RXUiWJbhOHqTThJAkEA5i5IOpmUmDl1\nHkYaf1cHbmCdnuQHI1YTlANAk/QsAdzfExK6tsTgIqSq5qd+Q38xtZJQrTvTT6p7\nJX+WQflunwJBAN8pdOrdr1tr1o8m958uLs33zjLk75ScnL+tqlCFEtZTVZWIXScB\n9YVZff5yYONfkuDK0kw631UMSxSA14vL71MCQQCbb+WWrN+LbEGKkAyUsVBzWQsX\noSSw2A+ghBG318tf9qctWhh8E7bHris6VyEMs3f+BTA1y5CG27kNOXteUfJBAkEA\n2QQDwvLaONlhycxnOdE7iujVCQFBSxASDwTff3Ypn2ti6wu1Kt3o2UjyEaNBPVwQ\nBbK3V5JY5OgTi1jQRA6KKQJAQiTQR1sA2xiUhYwF6K4hnojGW1Ew0ZBLND+APkej\nufcVAF5yh+ACYQPUMrgNwgcHFshCEJ9cpePZMotVy7zSFQ==\n-----END RSA PRIVATE KEY-----\n"
      - PORT=4000
    command: sh -c 'npm run dev'

networks:
  default:
    external:
      name: mydata
