version: '3.7'
services:
  operator-redis:
    image: redis:4.0-alpine
    environment:
      - REDIS_PASSWORD=fubar
    command: sh -c 'redis-server --requirepass $${REDIS_PASSWORD}'

  operator-postgres:
    image: postgres:11-alpine
    tmpfs: /pgtmpfs
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=mydata
      - PGDATA=/pgtmpfs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresuser -d mydata"]
      interval: 10s
      timeout: 5s
      retries: 5

  operator:
    image: node:11-alpine
    user: ${DC_U}:${DC_G}
    volumes:
      - ./../operator:/app
    ports:
      - 3001:3000
    environment:
      - PGHOST=operator-postgres
      - PGPORT=5432
      - REDIS=redis://:fubar@operator-redis:6379/
      - DATABASE_URL=postgres://postgresuser:postgrespassword@operator-postgres:5432/mydata
      - NODE_ENV=development
      - APM_SERVER=
    depends_on:
     - operator-postgres
     - operator-redis
    working_dir: /app
    command: sh -c 'node wait-for-postgres && npm run migrate up && npm run start:watch'

  cv-redis:
    image: redis:4.0-alpine
    environment:
      - REDIS_PASSWORD=fubar
    command: sh -c 'redis-server --requirepass $${REDIS_PASSWORD}'

  cv:
    image: node:11-alpine
    user: ${DC_U}:${DC_G}
    volumes:
      - ./../examples/cv:/app
    ports:
      - 4001:4000
    environment:
      - REDIS=redis://:fubar@cv-redis:6379/
      - NODE_ENV=development
      - CLIENT_ID=http://cv:4000
      - OPERATOR_URL=http://operator:3000
      - "PUBLIC_KEY=-----BEGIN RSA PUBLIC KEY-----\nMIGJAoGBAMinl3TDhzy/hZr+2ZrUMwveG+1eawsHqxUXOsdqARKfsBHTRYFPr+GW\nff9iNezU5yBBORtc/jVnPwto/lBhn2+jLCtcPuK5od8AEeiWGJbfL2np8P0/qg0O\n80qhLrMU47uuoEdTe9mbnB8A+N4OrC2WhPBj3zd9yAp1zLNPOk6NAgMBAAE=\n-----END RSA PUBLIC KEY-----\n"
      - "PRIVATE_KEY=-----BEGIN RSA PRIVATE KEY-----\nMIICXgIBAAKBgQDIp5d0w4c8v4Wa/tma1DML3hvtXmsLB6sVFzrHagESn7AR00WB\nT6/hln3/YjXs1OcgQTkbXP41Zz8LaP5QYZ9voywrXD7iuaHfABHolhiW3y9p6fD9\nP6oNDvNKoS6zFOO7rqBHU3vZm5wfAPjeDqwtloTwY983fcgKdcyzTzpOjQIDAQAB\nAoGBALGfGYV1KJvv9jdUbhCO03kn7pTbReqHqTyMSa4I+lYgId5FpXtorQsHCxYt\nPAsgFFELK6A7W5SuhrJ1CNri8Bxzh/7gYyj7njBTsjNfuoiK3cIkZBoTvY9K/OB+\nzinNKibWf3SZv9l1qFkaJvaC/+R5DMLb9RXUiWJbhOHqTThJAkEA5i5IOpmUmDl1\nHkYaf1cHbmCdnuQHI1YTlANAk/QsAdzfExK6tsTgIqSq5qd+Q38xtZJQrTvTT6p7\nJX+WQflunwJBAN8pdOrdr1tr1o8m958uLs33zjLk75ScnL+tqlCFEtZTVZWIXScB\n9YVZff5yYONfkuDK0kw631UMSxSA14vL71MCQQCbb+WWrN+LbEGKkAyUsVBzWQsX\noSSw2A+ghBG318tf9qctWhh8E7bHris6VyEMs3f+BTA1y5CG27kNOXteUfJBAkEA\n2QQDwvLaONlhycxnOdE7iujVCQFBSxASDwTff3Ypn2ti6wu1Kt3o2UjyEaNBPVwQ\nBbK3V5JY5OgTi1jQRA6KKQJAQiTQR1sA2xiUhYwF6K4hnojGW1Ew0ZBLND+APkej\nufcVAF5yh+ACYQPUMrgNwgcHFshCEJ9cpePZMotVy7zSFQ==\n-----END RSA PRIVATE KEY-----\n"
      - APM_SERVER=
    working_dir: /app
    depends_on:
     - operator-postgres
     - operator-redis
    command: sh -c 'npm start'

  app:
    image: node:11-alpine
    user: ${DC_U}:${DC_G}
    volumes:
      - ./../app:/app
    working_dir: /app
    ports:
      - 1337:1337
    depends_on:
      - operator
    environment:
      - OPERATOR_URL=http://operator:3000/api
    command: npm run e2e:server
